function R = registry()
%REGISTRY Every fabric estimator, grouped into the methods ptt.estimators.use selects.
%
% R = ptt.estimators.registry()
%
% A struct array, one entry per METHOD:
%   method    the name ptt.estimators.use takes
%   status    'production'  - what a pipeline runs
%             'reference'   - published, kept to compare against
%             'experimental'- not validated on real data
%             'superseded'  - replaced; kept so old results reproduce
%   summary   what the method is, in a sentence or two
%   members   struct array: name (what ptt.estimators.run takes) and
%             convention (which axis an angle names, in which frame, and
%             whether dlam is signed - the facts that differ between
%             methods and that every output now carries in .estimator)
%
% Every estimator belongs to exactly one method, and every file in
% +ptt/+estimators/private/ except the folder's own state is a member of
% one; test_estimators enforces both.
%
% See also ptt.estimators.use, ptt.estimators.run.

R = struct('method', {}, 'status', {}, 'summary', {}, 'members', {});

R(end+1) = H('quadpol_ls', 'production', ...
  ['Quad-pol coherence-field least squares, the estimator ' ...
   'run_quadpol_pipeline uses: a frame pass of geographic axes per ' ...
   'along-track segment, then per-block fits with that axis pinned.'], ...
  {'quadpolFabricLS', ...
   ['theta0 [rad]: the slow (lam_max) axis, along which the physics-sign ' ...
    'HH-VV phase grows, in the frame of the moments passed (antenna ' ...
    'unless pre-rotated). dlam >= 0 where the axis is searched; where it ' ...
    'is named (pinned, held, or a narrow grid) dlam = lam(theta0) - ' ...
    'lam(theta0 + 90), signed, positive when the named axis is the slow one.']; ...
   'quadpolFrameTheta', ...
   ['Segment axes [rad, geographic]: the slow axis as quadpolFabricLS ' ...
    'names it. One pedestal per frame, in the antenna frame.']; ...
   'quadpolJackknife', ...
   'Delete-one standard errors of a segment fit, in its units (rad, dlam).'; ...
   'thetaProfileAt', ...
   ['A frame pass''s geographic axis profile at one along-track position, ' ...
    'interpolated on the doubled-angle phasor.']});

R(end+1) = H('ershadi', 'reference', ...
  ['Ershadi et al. (2022): the published direct chain and its Sect. 3.5 ' ...
   'fit. On this system''s uncalibrated channels the cross-pol minimum ' ...
   'it reads the axis from sits on the antennas.'], ...
  {'ershadiFabric', ...
   ['theta [rad]: the lam_max axis, from the cross-pol extinction ' ...
    'minimum, antenna frame. dlam = |Psi| >= 0, the phase gradient read ' ...
    'at that axis.']; ...
   'ershadiInverse', ...
   ['Piecewise theta [rad] in ershadiFabric''s sense and r_dB = ' ...
    '20 log10(Gamma_y/Gamma_x); dlam is accepted from the input, not fitted.']; ...
   'ershadiStrength', ...
   'dlam(z) given ershadiInverse''s theta and r.'});

R(end+1) = H('nymand', 'experimental', ...
  ['The NEGIS two-step scheme: orientation and scattering ratio from ' ...
   'powers under a constant eigenframe, then dlam from travel-time ' ...
   'anomalies by linear maximum likelihood.'], ...
  {'polarimetricInverse', ...
   ['One theta0 [rad] for the column and r(z) = S22/S11, from azimuthal ' ...
    'power anomalies; d = theta0 - psi in the synthesis sense.']; ...
   'polarimetricRatioInverse', ...
   ['One theta0 [rad] in the frame of obs.gamma, dlam(z) >= 0 and r(z), ' ...
    'from channel power ratios with a free gain offset each; theta0 is ' ...
    'known only mod 90 unless the co-pol phase is used.']; ...
   'traveltimeFabricML', ...
   ['dlam(z) = lam_x - lam_y for the polarizations the delays dtau = ' ...
    't_x - t_y were measured between; exact linear-Gaussian posterior.']; ...
   'nymandTwoStep', ...
   'polarimetricInverse then traveltimeFabricML, alternated until both settle.'});

R(end+1) = H('gls', 'experimental', ...
  ['Generalized least squares for theta(z), dlam(z) and r(z) profiles ' ...
   'under the layered Fujita model, with a linearised posterior.'], ...
  {'fabricGLS', ...
   ['theta_z [rad], dlam_z and rdb_z with one-sigma profiles; the ' ...
    'posterior is a linearisation, measured optimistic.']});

R(end+1) = H('copol', 'production', ...
  ['Co-polarized travel-time inversion (Rathmann 2026, common offset), ' ...
   'the estimator the OPR fabric module (fabric_task) uses.'], ...
  {'invertHorizontalFabric', ...
   ['dlam = lam_x - lam_y per reflector interval for the delays dtau = ' ...
    't_x - t_y supplied (the OPR module supplies t_VV - t_HH, so x is the ' ...
    'rotated V axis); exact layer stripping.']; ...
   'invertHorizontalFabricJoint', ...
   ['dlam as invertHorizontalFabric defines it, from a joint ' ...
    'smoothness-regularised solve with a reference-offset nuisance.']; ...
   'invertBlocks', ...
   'Per-block driver of the two above; dlam as they define it.'});

R(end+1) = H('cmp', 'reference', ...
  ['Rathmann (2026) CMP inversion. Needs varying Tx-Rx offsets, which ' ...
   'this radar does not record.'], ...
  {'invertFabric', ...
   ['f = (zhat_bco, lam_x and lam_z at the surface and bed): linear ' ...
    'eigenvalue profiles with lam_y by normalisation.']});

R(end+1) = H('direct', 'superseded', ...
  'The first quad-pol estimator, replaced by quadpol_ls.', ...
  {'quadpolFabric', ...
   ['theta [rad] from the cross-pol 4-psi harmonic (mod 90), resolved by ' ...
    'the sign of the phase gradient; dlam = lam_max - lam_min.']});

R(end+1) = H('power', 'experimental', ...
  'Fabric from co-polarized power alone, for ice where the HH-VV coherence is gone.', ...
  {'quadpolFabricPower', ...
   ['Axis [rad] mod 90, resolved by r_db only where |r_db| is large; ' ...
    '|dlam| as a magnitude, which reads high where the reflection ratio varies.']});
end

function e = H(method, status, summary, members)
e = struct('method', method, 'status', status, 'summary', summary, ...
  'members', cell2struct(members, {'name', 'convention'}, 2));
end
