%TEST_LS_VS_FUJITA The production LS fit, against the Fujita matrix model.
%
% ptt.quadpolFabricLS never calls ptt.fujitaModel. It fits a CLOSED FORM
% for the coherence of one homogeneous birefringent column, which is the
% Fujita et al. (2006) matrix collapsed for a single layer with a fixed
% axis. That collapse is exact, but until this test nothing checked it:
% test_quadpol_ls builds its synthetic from the same closed form the
% estimator fits (hh = cos^2 d e^{i delta} + sin^2 d, and so on), so it
% could only ever confirm the estimator is self-consistent.
%
% This runs the data through the MATRIX instead, so the two independent
% implementations of the same physics have to agree.
%
%   1. ONE LAYER, FIXED AXIS. Data generated by ptt.fujitaModel and
%      inverted by ptt.quadpolFabricLS must return the contrast that went
%      in, and the axis under a convention this verdict PINS.
%
%      THE AXIS COMES BACK 90 DEGREES ROUND, and that is correct. MEASURED
%      over theta = 0, 20, 35, 50, 70, 110 deg, the LS returns exactly
%      theta + 90 every time. The two implementations name the two
%      ORTHOGONAL principal axes: fujitaModel's `theta` labels one
%      eigenvalue of the layer, while ptt.quadpolFabricLS defines theta0 as
%      the axis along which the deramped phase GROWS with depth (its own
%      header says so). They agree about the ice and disagree about which
%      axis gets the name.
%
%      This is a DIFFERENT relation from the one already documented for
%      ptt.polarimetricInverse, which is theta -> -theta and is pinned in
%      test_polarimetric_inverse. Two reductions of the same matrix, two
%      different conventions, and this one was neither written down nor
%      tested until now. Scoring it here is the point: a convention that
%      lives only in someone's head is one refactor from silently negating
%      or rotating every axis this project reports.
%   2. WHERE THE COLLAPSE STOPS BEING EXACT. Give the matrix a column
%      whose axis TURNS with depth, which no single-column closed form can
%      represent, and the LS must degrade. This verdict exists so the
%      limitation is measured rather than assumed: it is the same
%      constant-eigenframe assumption that the constant-orientation mode
%      makes explicit, and the number here says what it costs.
%
% Run: matlab -batch "run('opr_fabric/test/test_ls_vs_fujita.m')"
clear; t0 = tic;
thisDir = fileparts(mfilename('fullpath'));
addpath(fullfile(thisDir, '..', '..'));

fc = 750e6; z = (10:10:1200).'; Nz = numel(z); Nx = 600;
TH = deg2rad(35); DL = 0.05;
C = ptt.constants(); n_ice = sqrt(C.eps_bar);
gpd = 2*pi*fc * 2 * (C.deps/(2*n_ice)) / (C.c*1e9);
OPTS = struct('fc', fc, 'psi_step_deg', 3, 'win_fit_m', 120, 'step_m', 60, ...
  'deramped', true, 'pedestal', 'window');

%% ---- verdict 1: one layer, fixed axis
lay = struct('top_m', 0, 'dlam', DL, 'theta', TH, 'r_db', 0, 'gx_db', 0);
fm = ptt.fujitaModel(lay, z, 0, struct('fc', fc, 'win_m', 30));
S = H_speckle(fm, Nx, 0);
o = ptt.quadpolFabricLS(S, z, OPTS);
th_hat = angle(median(exp(2i*o.theta0(isfinite(o.theta0)))))/2;
% the LS names the orthogonal axis: expect theta + 90 deg (see the header)
eth = rad2deg(abs(angle(exp(2i*(th_hat - (TH + pi/2))))/2));
dl_hat = median(o.dlam(isfinite(o.dlam)));
fprintf('1. matrix in, LS out: theta %.1f deg (matrix %.1f, expect +90 = %.1f)\n', ...
  mod(rad2deg(th_hat),180), rad2deg(TH), mod(rad2deg(TH)+90,180));
fprintf('   theta err %.2f deg, dlam %.4f (truth %.4f)\n', eth, dl_hat, DL);
ok1 = eth < 5 && abs(dl_hat - DL) < 0.008;
fprintf('   the closed form agrees with the matrix:                %s\n', H_tick(ok1));

%% ---- verdict 2: a turning axis, which the closed form cannot represent
nL = 6; top = (0:nL-1).' * (max(z)/nL);
TH_ROT = TH + deg2rad(60) * (top/max(top));
lay2 = struct('top_m', num2cell(top), 'dlam', num2cell(DL*ones(nL,1)), ...
  'theta', num2cell(TH_ROT), 'r_db', num2cell(zeros(nL,1)), ...
  'gx_db', num2cell(zeros(nL,1)));
fm2 = ptt.fujitaModel(lay2, z, 0, struct('fc', fc, 'win_m', 30));
S2 = H_speckle(fm2, Nx, 0);
o2 = ptt.quadpolFabricLS(S2, z, OPTS);
zw = o2.zw(:); th2 = o2.theta0(:);
g2 = isfinite(th2);
th_true_w = interp1(top, TH_ROT, zw, 'linear', 'extrap') + pi/2;
e_rot = rad2deg(median(abs(angle(exp(2i*(th2(g2) - th_true_w(g2))))/2)));
spread = rad2deg(abs(angle(max(exp(2i*th2(g2))) ./ min(exp(2i*th2(g2))))))/2; %#ok<NASGU>
resid1 = median(o.resid(isfinite(o.resid)));
resid2 = median(o2.resid(isfinite(o2.resid)));
fprintf('\n2. turning axis (60 deg over the column):\n');
fprintf('   misfit: fixed axis %.4f, turning axis %.4f (%.1fx worse)\n', ...
  resid1, resid2, resid2/max(resid1, eps));
fprintf('   (per-window axis departs the layer truth by %.1f deg - reported,\n', e_rot);
fprintf('    not asserted: over a window whose ice turns, the single axis the\n');
fprintf('    LS fits has no unambiguous truth to be scored against)\n');
% Asserted on the MISFIT alone. That is the unambiguous statement: the
% closed form cannot represent a turning column, so it must fit it worse.
% The axis error is reported because its reference is ill-defined here -
% scoring it moved from 14 to 51 deg purely with the convention chosen for
% the per-window truth, which is a sign it is not a clean assertion.
ok2 = resid2 > 3 * resid1;
fprintf('   the single-column collapse degrades, measurably:       %s\n', H_tick(ok2));

fails = ~ok1 + ~ok2;
fprintf('\n%s (%.1f min)\n', H_tick(fails == 0), toc(t0)/60);
if fails > 0
  error('test_ls_vs_fujita:failed', '%d verdict(s) failed', fails);
end

function S = H_speckle(fm, Nx, na)
% one deterministic column times circular speckle, so the estimator sees
% the statistics it expects while the DETERMINISTIC field is the matrix's
r = (randn(size(fm.s_hh,1), Nx) + 1i*randn(size(fm.s_hh,1), Nx)) / sqrt(2);
S = struct();
S.hh = fm.s_hh(:,1) .* r; S.vv = fm.s_vv(:,1) .* r;
S.hv = fm.s_hv(:,1) .* r; S.vh = fm.s_hv(:,1) .* r;
if na > 0
  f = @(A) A + na*(randn(size(A))+1i*randn(size(A)));
  S.hh = f(S.hh); S.vv = f(S.vv); S.hv = f(S.hv); S.vh = f(S.vh);
end
end

function s = H_tick(ok)
if ok, s = 'PASS'; else, s = 'FAIL'; end
end
