%TEST_FABRIC_GLS Generalized least squares fabric inversion, and its uncertainty.
%
% ptt.fabricGLS inverts the full layered Fujita model for theta(z), dlam(z)
% and r(z) as PROFILES, with a prior instead of a hard constant-orientation
% constraint, and returns a linearised posterior covariance.
%
%   1. RECOVERY. Noise-free data generated by the same forward model is
%      recovered: theta within 2 deg, dlam within 0.006, chi2/dof ~ 0.
%   2. CHI-SQUARE. With noise at exactly the level C_d assumes, the reduced
%      chi-square lands near 1. Far from 1 means C_d is wrong, which would
%      make every reported sigma wrong with it.
%   3. UNCERTAINTY CALIBRATION - THE VERDICT THAT MATTERS. A posterior is
%      worthless unless the errors actually scatter by about the sigma it
%      quotes. R independent noisy realisations are inverted and the
%      empirical scatter is compared with the reported sigma. This is the
%      same standard applied to the resampling uncertainty in
%      test_quadpol_uncertainty, and it is applied here because a
%      LINEARISED posterior on a strongly non-linear, multi-modal problem
%      has every reason to be optimistic. It is: MEASURED over 16
%      realisations, both theta and dlam scatter about twice as far as the
%      posterior claims, so the reported sigmas are LOWER BOUNDS and are
%      documented as such rather than quietly widened by a fudge factor.
%   5. CORRELATED AZIMUTHS. Verdicts 1-4 give the solver independent noise,
%      which real synthesized azimuths never have. Under noise confined to
%      a rank-4 azimuthal subspace the diagonal posterior is NOT optimistic
%      for dlam: the reported sigma over the ROBUST empirical scatter
%      (1.4826 * MAD) is about 1.00, and opts.n_indep_psi = 4, which
%      multiplies every sigma by sqrt(18/4) = 2.1, overshoots to about
%      1.59. The verdict asserts that naive calibration and the overshoot,
%      so the option stays off for channel-synthesised azimuths. The scatter
%      is robust because the solver occasionally stops in a nearby local
%      minimum (issue #28), which a converged solver does not produce: an
%      earlier revision of this branch read a plain std over the 16
%      realisations, where two unconverged ones (5 and 15, 7 and 5 robust
%      sigmas off the cluster) made the naive posterior look 2.6x
%      optimistic (0.38). That reading was wrong; correcting the forward
%      (issue #29) did not change the conclusion. The std-based ratios and
%      the count of such outliers are printed beside the robust ones.
%
%   4. THE ORIENTATION PRIOR IS A PRIOR, NOT A CONSTRAINT. Given a column
%      whose axis really does rotate with depth, a long theta correlation
%      length holds the axis nearly constant and cannot follow it, while a
%      short one tracks the true profile. Scored against the true profile
%      circularly, because theta is an axis and each layer may sit on
%      either branch. That is the whole point
%      of moving from ptt.polarimetricRatioInverse to this: the
%      constant-orientation assumption becomes a number the data argues
%      with, and the test asserts the data can win.
%
% Run: matlab -batch "run('opr_fabric/test/test_fabric_gls.m')"
clear; t0 = tic;
thisDir = fileparts(mfilename('fullpath'));
addpath(fullfile(thisDir, '..', '..'));

fc = 750e6; z = (10:10:1400).'; psi = (0:10:170)*pi/180;
nL = 8; top = (0:nL-1).' * (1400/nL);
TH = deg2rad(35);
DLv = 0.03 + 0.04*(top/1400);
NLOOK = 20;
S_DB = (10/log(10)) * sqrt(psi_trigamma(NLOOK));

fm = H_fwd(top, DLv, TH*ones(nL,1), zeros(nL,1), z, psi, fc);
obs0 = struct('psi', psi, 'dP_hh', fm.dP_hh, 'dP_hv', fm.dP_hv, ...
  'phi', fm.phi, 'Cmag', fm.Cmag);
BASE = struct('fc', fc, 'n_layer', nL, 'n_looks', NLOOK, 'max_iter', 30, 'n_start', 3);

o1 = ptt.fabricGLS(obs0, z, BASE);
e_th = rad2deg(abs(angle(exp(2i*(median(o1.theta_z) - TH)))/2));
dl_true_z = interp1(top, DLv, z, 'linear', 'extrap');
e_dl = median(abs(o1.dlam_z - dl_true_z));
fprintf('1. noise-free: theta err %.2f deg, dlam err %.4f, chi2/dof %.2f\n', e_th, e_dl, o1.chi2_dof);
ok1 = e_th < 2 && e_dl < 0.006;
fprintf('   recovers the profiles:                                %s\n', H_tick(ok1));

rng(11);
o2 = ptt.fabricGLS(H_noise(obs0, S_DB, NLOOK), z, BASE);
fprintf('\n2. with noise at the assumed level: chi2/dof %.2f\n', o2.chi2_dof);
ok2 = o2.chi2_dof > 0.3 && o2.chi2_dof < 3;
fprintf('   C_d is the right size:                                %s\n', H_tick(ok2));

R = 16;
th_hat = nan(R,1); dl_hat = nan(R,1); s_th = nan(R,1); s_dl = nan(R,1);
for k = 1:R
  rng(100+k);
  ok = ptt.fabricGLS(H_noise(obs0, S_DB, NLOOK), z, BASE);
  th_hat(k) = ok.theta_z(round(end/2));
  dl_hat(k) = ok.dlam_z(round(end/2));
  s_th(k) = ok.sigma_theta_z(round(end/2));
  s_dl(k) = ok.sigma_dlam_z(round(end/2));
end
emp_th = rad2deg(std(th_hat)); rep_th = rad2deg(median(s_th));
emp_dl = std(dl_hat); rep_dl = median(s_dl);
r_th = rep_th / max(emp_th, eps); r_dl = rep_dl / max(emp_dl, eps);
fprintf('\n3. calibration over %d realisations, at mid-column:\n', R);
fprintf('   theta: empirical %.3f deg, reported %.3f deg -> ratio %.2f\n', emp_th, rep_th, r_th);
fprintf('   dlam : empirical %.5f,   reported %.5f   -> ratio %.2f\n', emp_dl, rep_dl, r_dl);
ok3 = r_th > 0.3 && r_th < 3 && r_dl > 0.3 && r_dl < 3;
fprintf('   the posterior matches the actual scatter:              %s\n', H_tick(ok3));
% Printed from the measured ratios rather than asserted, so the number
% cannot go stale when the solver changes. At 16 realisations both
% parameters land near 0.5: the linearised posterior is optimistic by
% roughly 2x, which is the expected price of linearising a problem this
% non-linear and is why the header refuses to trust it unchecked.
fprintf('   NOTE both near 0.5 -> the linearised posterior is OPTIMISTIC by\n');
fprintf('        about %.1fx (theta) and %.1fx (dlam). Treat sigma_theta_z and\n', ...
  1/max(r_th,eps), 1/max(r_dl,eps));
fprintf('        sigma_dlam_z as LOWER BOUNDS on the real uncertainty.\n');

% rotating column: the axis turns 50 deg over the record
TH_ROT = TH + deg2rad(50) * (top/max(top));
fm_r = H_fwd(top, DLv, TH_ROT, zeros(nL,1), z, psi, fc);
obs_r = struct('psi', psi, 'dP_hh', fm_r.dP_hh, 'dP_hv', fm_r.dP_hv, ...
  'phi', fm_r.phi, 'Cmag', fm_r.Cmag);
th_true_z = interp1(top, TH_ROT, z, 'linear', 'extrap');
o_f = ptt.fabricGLS(obs_r, z, BASE);
% scored against the TRUE profile, circularly. theta is an AXIS, unique
% only modulo 180 deg, so each layer may sit on either branch: a raw
% max-minus-min of theta_z reported a 278 deg "swing" for a 50 deg
% rotation and said nothing about whether the rotation was recovered.
err_f = rad2deg(median(abs(angle(exp(2i*(o_f.theta_z - th_true_z)))/2)));

% The best CONSTANT axis, fit the same way: sigma tight enough to freeze
% theta, prior mean scanned so the constant axis is chosen by the data
% rather than assumed. This is the GLS equivalent of the theta_const mode.
%
% It has to be scanned rather than stiffened by corr_len alone. A prior at
% the default sigma of pi/2 permits sigma*sqrt(1-exp(-dz/L)) of
% layer-to-layer wander, and MEASURED, even L = 1e8 m (0.12 deg of
% permitted wander) still tracks this rotation, because the data term is
% five orders of magnitude larger than the prior penalty it pays to bend.
% That is the honest headline: on data this informative the orientation
% prior does not constrain the answer, it only breaks ties.
gr = deg2rad(0:15:165);
chi_c = nan(size(gr));
for k = 1:numel(gr)
  cf = BASE; cf.theta_prior = [gr(k), deg2rad(0.05), 1e8]; cf.n_start = 1;
  chi_c(k) = ptt.fabricGLS(obs_r, z, cf).chi2_dof;
end
chi_rot = min(chi_c);

% Control on the CONSTANT-axis column, so the verdict cannot pass merely
% because a tight prior always fits badly.
chi_c0 = nan(size(gr));
for k = 1:numel(gr)
  cf = BASE; cf.theta_prior = [gr(k), deg2rad(0.05), 1e8]; cf.n_start = 1;
  chi_c0(k) = ptt.fabricGLS(obs0, z, cf).chi2_dof;
end
chi_con = min(chi_c0);

fprintf('\n4. rotating column (true swing 50 deg):\n');
fprintf('   free axis:           median |theta err| %.1f deg, chi2/dof %.3g\n', err_f, o_f.chi2_dof);
fprintf('   best constant axis:  chi2/dof %.3g  -> rejected\n', chi_rot);
fprintf('   same fit on a genuinely constant column: chi2/dof %.3g -> accepted\n', chi_con);
ok4 = err_f < 6 && chi_rot > 20 && chi_con < 1;
fprintf('   constant orientation is falsifiable, not assumed:      %s\n', H_tick(ok4));

% ---- verdict 5: correlated azimuth noise, the real-data case
% Synthesized azimuths are linear combinations of four measured channels,
% so their noise lives in a four-dimensional azimuthal subspace rather
% than in Np independent samples. The HYPOTHESIS behind opts.n_indep_psi
% was that a diagonal C_d, counting every azimuth as fresh evidence, must
% therefore report sigmas that are too tight, and that setting n_indep_psi
% = 4 would move the calibration ratio back toward 1. This verdict tests
% that hypothesis on noise built to break it; what it measures is below,
% and it is not what was expected.
R5 = 16;
[d_naive, d_corr, s_naive, s_corr] = deal(nan(R5,1));
CORR = BASE; CORR.n_indep_psi = 4;
for k = 1:R5
  rng(500+k);
  on = H_noise_corr(obs0, S_DB, NLOOK, psi);
  a = ptt.fabricGLS(on, z, BASE);
  b = ptt.fabricGLS(on, z, CORR);
  d_naive(k) = a.dlam_z(round(end/2)); s_naive(k) = a.sigma_dlam_z(round(end/2));
  d_corr(k)  = b.dlam_z(round(end/2)); s_corr(k)  = b.sigma_dlam_z(round(end/2));
end
% robust scatter: realisations the solver leaves in a nearby local
% minimum (issue #28) are not posterior scatter, and a plain std counts
% them as if they were
rsd = @(d) 1.4826 * mad(d, 1);
n_out = @(d) sum(abs(d - median(d)) > 5 * rsd(d));
rn = median(s_naive) / max(rsd(d_naive), eps);
rc = median(s_corr)  / max(rsd(d_corr),  eps);
fprintf('\n5. azimuth noise with only 4 independent modes, dlam at mid-column:\n');
fprintf('   assuming independence: reported/empirical %.2f (std-based %.2f, %d solver outlier(s) beyond 5 robust sigmas)\n', ...
  rn, median(s_naive) / max(std(d_naive), eps), n_out(d_naive));
fprintf('   with n_indep_psi = 4:  reported/empirical %.2f (std-based %.2f, %d solver outlier(s) beyond 5 robust sigmas)\n', ...
  rc, median(s_corr) / max(std(d_corr), eps), n_out(d_corr));
% MEASURED on the corrected forward model: confining the noise to four
% azimuthal modes leaves the diagonal posterior calibrated for dlam (naive
% robust ratio about 1.00), and n_indep_psi = 4 multiplies every sigma by
% sqrt(Np/4) = 2.1 and overshoots (about 1.59). An earlier revision of
% this branch read std over the 16 realisations, where two unconverged
% realisations (5 and 15) made the naive posterior look 2.6x optimistic
% (0.38); that reading was wrong, and correcting the forward (issue #29)
% did not change the conclusion. The option stays off for synthesised
% azimuths.
ok5 = rn > 0.5 && rn < 2 && rc > 1.4 * rn;
fprintf('   naive posterior calibrated, n_indep_psi = 4 overshoots: %s\n', H_tick(ok5));

fails = ~ok1 + ~ok2 + ~ok3 + ~ok4 + ~ok5;
fprintf('\n%s (%.1f min)\n', H_tick(fails == 0), toc(t0)/60);
if fails > 0
  error('test_fabric_gls:failed', '%d verdict(s) failed', fails);
end

function fm = H_fwd(top, dl, th, rdb, z, psi, fc)
nL = numel(top);
lay = struct('top_m', num2cell(top), 'dlam', num2cell(dl), ...
  'theta', num2cell(th), 'r_db', num2cell(rdb), 'gx_db', num2cell(zeros(nL,1)));
fm = ptt.fujitaModel(lay, z, psi, struct('fc', fc, 'win_m', 30));
end

function o = H_noise(obs0, s_db, nlook)
o = obs0;
o.dP_hh = obs0.dP_hh + s_db*randn(size(obs0.dP_hh));
o.dP_hv = obs0.dP_hv + s_db*randn(size(obs0.dP_hv));
c = min(max(obs0.Cmag, 1e-3), 0.999);
o.phi = obs0.phi + sqrt((1-c.^2)./(2*nlook*c.^2)) .* randn(size(obs0.phi));
end

function o = H_noise_corr(obs0, s_db, nlook, psi)
% Noise confined to a rank-4 azimuthal subspace, standing in for azimuths
% synthesized from four measured channels. Each basis column is unit-RMS
% over azimuth and the coefficients are scaled by 1/sqrt(4) so the
% PER-SAMPLE standard deviation still comes out at s_db: the amount of
% noise is unchanged, only its independence across azimuth.
B = [ones(numel(psi),1), cos(2*psi(:)), sin(2*psi(:)), cos(4*psi(:))];
B = B ./ sqrt(mean(B.^2, 1));
o = obs0;
g = @(A) A + (randn(size(A,1), 4) * B.') * (s_db/2);
o.dP_hh = g(obs0.dP_hh);
o.dP_hv = g(obs0.dP_hv);
c = min(max(obs0.Cmag, 1e-3), 0.999);
sp = sqrt((1-c.^2)./(2*nlook*c.^2));
o.phi = obs0.phi + sp .* (randn(size(sp,1), 4) * B.') / 2;
end

function y = psi_trigamma(n)
y = psi(1, n);
end

function s = H_tick(ok)
if ok, s = 'PASS'; else, s = 'FAIL'; end
end
